// Exhibition detail pages stay in jadeExhibitions. CV / presentation records live in
// jadePresentationHistory so Series and About can show both linked and unlinked history.
window.jadeExhibitions = [
  {
    id: "dandelion-paris-cite",
    seriesId: "dandelion-has-not-decided",
    year: "2026",
    titleZh: "《地丁》- 巴黎国际艺术城",
    titleEn: "The Dandelion Has Not Decided - Cité Internationale des Arts",
    workZh: "《地丁》",
    workEn: "The Dandelion Has Not Decided",
    venueZh: "巴黎国际艺术城",
    venueEn: "Cité Internationale des Arts, Paris",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "works/dandelion-has-not-decided/images/exhibition/00-poster.jpg",
    images: [
      {
        src: "works/dandelion-has-not-decided/images/exhibition/00-poster.jpg",
        captionZh: "展览海报",
        captionEn: "Exhibition Poster",
      },
      "works/dandelion-has-not-decided/images/exhibition/01.jpg",
      "works/dandelion-has-not-decided/images/exhibition/02.jpg",
      "works/dandelion-has-not-decided/images/exhibition/03.jpg",
      "works/dandelion-has-not-decided/images/exhibition/04.jpg",
      "works/dandelion-has-not-decided/images/exhibition/05.jpg",
      {
        src: "works/dandelion-has-not-decided/images/exhibition/06-opposite-window.jpg",
        captionZh: "合作视频《对面的窗户》现场",
        captionEn: "Collaborative Video: The Opposite Window, Exhibition Site",
      },
      "works/dandelion-has-not-decided/images/exhibition/07.jpg",
      "works/dandelion-has-not-decided/images/exhibition/08.jpg",
      "works/dandelion-has-not-decided/images/exhibition/09.jpg",
    ],
    sources: [],
  },
  {
    id: "dandelion-caijiapo",
    seriesId: "hesitation",
    year: "2026",
    titleZh: "《地丁并未决定》- 蔡家坡村村史馆",
    titleEn: "Hesitation - Caijiapo Village History Museum",
    workZh: "《地丁并未决定》",
    workEn: "Hesitation",
    venueZh: "蔡家坡村村史馆",
    venueEn: "Caijiapo Village History Museum",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/00.jpg",
    images: [
      {
        src: "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/00.jpg",
        captionZh: "展览作品分享会海报",
        captionEn: "Exhibition Works Sharing Session Poster",
      },
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/01.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/02.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/03.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/04.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/05.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/caijiapo/06.jpg",
    ],
    sources: [
      {
        label: "展讯",
        labelEn: "Notice",
        href: "https://mp.weixin.qq.com/s/t3MCPd7b1_W-XLnAM0Usng",
      },
      {
        label: "访谈",
        labelEn: "Interview",
        href: "https://mp.weixin.qq.com/s/lwQJZvccumQpvJSII7_nRA",
      },
      {
        label: "分享会",
        labelEn: "Talk",
        href: "https://mp.weixin.qq.com/s/ub_BqMOQiz6od68IsPIRiA",
      },
    ],
  },
  {
    id: "yishu-arles",
    seriesId: "epitaph",
    year: "2024",
    titleZh: "《疑树》- 法国阿尔勒",
    titleEn: "Epitaph - Arles, France",
    workZh: "《疑树》",
    workEn: "Epitaph",
    venueZh: "法国阿尔勒",
    venueEn: "Arles, France",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/arles/01.jpg",
    images: ["About _ Jade Tongxin Ji_files/exhibition-assets/arles/01.jpg"],
    sources: [
      {
        label: "Fisheye 10sur10 | Arles",
        labelEn: "Fisheye 10sur10 | Arles",
        href: "https://www.instagram.com/p/C8XP2bNh8up/",
      },
    ],
  },
  {
    id: "yishu-lishui",
    seriesId: "epitaph",
    year: "2025",
    titleZh: "《疑树》- 丽水摄影节",
    titleEn: "Epitaph - Lishui Photography Festival",
    workZh: "《疑树》",
    workEn: "Epitaph",
    venueZh: "丽水摄影节",
    venueEn: "Lishui Photography Festival",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/lishui/01.jpg",
    images: [
      "About _ Jade Tongxin Ji_files/exhibition-assets/lishui/01.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/lishui/02.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/lishui/03.jpg",
    ],
    sources: [
      {
        label: "第六届国际摄影研讨会暨2025丽水摄影节院校组",
        labelEn: "6th International Photography Symposium and 2025 Lishui Photography Festival, Academy Section",
        href: "https://mp.weixin.qq.com/s/TNFbOh-PdPOX7LaYunMDIQ",
      },
    ],
  },
  {
    id: "new-year-elevator",
    seriesId: "new-year-elevator",
    year: "2024",
    titleZh: "《新年电梯》- 浓缩城市计划",
    titleEn: "New Year Elevator - Condensed City Project",
    workZh: "《新年电梯》",
    workEn: "New Year Elevator",
    venueZh: "浓缩城市计划",
    venueEn: "Condensed City Project",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/01.jpg",
    images: [
      "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/01.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/02.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/03-installation-view.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/03.jpg",
      {
        src: "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/04.jpg",
        captionZh: "对谈现场",
        captionEn: "Conversation Scene",
      },
      {
        src: "About _ Jade Tongxin Ji_files/exhibition-assets/elevator/05.jpg",
        captionZh: "对谈现场",
        captionEn: "Conversation Scene",
      },
    ],
    sources: [
      {
        label: "浓缩城市计划｜新年电梯",
        labelEn: "Condensed City Project | New Year Elevator",
        href: "https://mp.weixin.qq.com/s/rDohgO0DUqM71W0Vcr231Q",
      },
      {
        label: "浓缩城市计划｜新年电梯现场回顾",
        labelEn: "Condensed City Project | New Year Elevator, Exhibition Review",
        href: "https://mp.weixin.qq.com/s/g0NZKTzK4BELyUWcdBLGjw",
      },
    ],
  },
  {
    id: "yishu-pingyao",
    seriesId: "epitaph",
    year: "2024",
    titleZh: "《疑树》- 平遥国际摄影大展",
    titleEn: "Epitaph - Pingyao International Photography Festival",
    workZh: "《疑树》",
    workEn: "Epitaph",
    venueZh: "平遥国际摄影大展",
    venueEn: "Pingyao International Photography Festival",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/pingyao/01.jpg",
    images: [
      "About _ Jade Tongxin Ji_files/exhibition-assets/pingyao/01.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/pingyao/02.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/pingyao/03.jpg",
    ],
    sources: [
      {
        label: "第24届平遥国际摄影大展揭晓各大奖项",
        labelEn: "The 24th Pingyao International Photography Festival Announces Its Awards",
        href: "https://mp.weixin.qq.com/s/YxM7dSAcJ9uTc_eQJ8eoLA",
      },
    ],
  },
  {
    id: "yishu-sichuan",
    seriesId: "epitaph",
    year: "2024",
    titleZh: "《疑树》- 四川美术学院美术馆",
    titleEn: "Epitaph - Sichuan Fine Arts Institute Art Museum",
    workZh: "《疑树》",
    workEn: "Epitaph",
    venueZh: "四川美术学院美术馆",
    venueEn: "Sichuan Fine Arts Institute Art Museum",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/sichuan/01-exhibition-site.jpg",
    images: [
      "About _ Jade Tongxin Ji_files/exhibition-assets/sichuan/01-exhibition-site.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/sichuan/02-original.jpg",
    ],
    sources: [
      {
        label: "第四届“未来·星丛”奖美术与书法优秀作品展",
        labelEn: "The 4th Future Star Cluster Award Exhibition of Outstanding Works in Fine Arts and Calligraphy",
        href: "https://mp.weixin.qq.com/s/X3LlD26Mxw_qwzvoXEUTDw",
      },
    ],
  },
  {
    id: "yishu-xian",
    seriesId: "epitaph",
    year: "2024",
    titleZh: "《疑树》- 西安美术馆",
    titleEn: "Epitaph - Xi'an Art Museum",
    workZh: "《疑树》",
    workEn: "Epitaph",
    venueZh: "西安美术馆",
    venueEn: "Xi'an Art Museum",
    artist: "纪彤心 / Jade Tongxin Ji",
    cover: "About _ Jade Tongxin Ji_files/exhibition-assets/xian/01.jpg",
    images: [
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/01.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/02.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/03.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/04.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/05.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/06.jpg",
      "About _ Jade Tongxin Ji_files/exhibition-assets/xian/07.jpg",
    ],
    sources: [
      {
        label: "西安美术学院影视动画系2024届本科毕业作品展",
        labelEn: "2024 Undergraduate Graduation Exhibition, Department of Film and Animation, Xi'an Academy of Fine Arts",
        href: "http://mp.weixin.qq.com/s?__biz=MzA4MTEyNjcxOA==&mid=2712144063&idx=2&sn=21f0f88a01bdb534530547119c87a2a6&chksm=bbc51cee8cb295f88281bea21be616b016cebe9307fd9febcad96f450f6d6825853414e59ef3&mpshare=1&scene=2&srcid=061999jFDtdTsy0NyPdzvcWe&sharer_shareinfo=3f5010105d522cd01b9620f46677afd4&sharer_shareinfo_first=ad0752729a2050abe9fad0fd6a2e5e9f#rd",
      },
      {
        label: "《疑树》_纪彤心作品_2024西安美术学院本科毕业作品展",
        labelEn: "Epitaph by Jade Tongxin Ji, 2024 Undergraduate Graduation Exhibition, Xi'an Academy of Fine Arts",
        href: "https://xafa.meishu.org.cn/arts/4403-112463.html",
      },
    ],
  },
];

window.jadePresentationHistory = [
  {
    year: "2026",
    seriesId: "dandelion-has-not-decided",
    workZh: "《地丁》",
    workEn: "The Dandelion Has Not Decided",
    eventZh: "《地丁》个展",
    eventEn: "The Dandelion Has Not Decided, solo exhibition",
    detailId: "dandelion-paris-cite",
  },
  {
    year: "2026",
    seriesId: "hesitation",
    workZh: "《地丁并未决定》",
    workEn: "Hesitation",
    eventZh: "《地丁并未决定》个展",
    eventEn: "Hesitation, solo exhibition",
    detailId: "dandelion-caijiapo",
  },
  {
    year: "2025",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "丛生——首届两岸艺术双年展，“浪隙之屿”单元，参展",
    eventEn: "Congsheng: The First Cross-Strait Art Biennial, Islands in the Wave Gaps section, exhibited",
  },
  {
    year: "2025",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "第六届国际摄影研讨会暨2025丽水摄影节院校组，参展",
    eventEn: "6th International Photography Symposium and 2025 Lishui Photography Festival, Academy Section, exhibited",
    detailId: "yishu-lishui",
  },
  {
    year: "2025",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "2025年度仁川开放港国际大学生摄影节，入围",
    eventEn: "Incheon Open Port International University Student Photography Festival, shortlisted",
  },
  {
    year: "2025",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "“关注与共鸣——陕西省高校优秀数字影像展”，参展",
    eventEn: "Attention and Resonance: Outstanding Digital Image Exhibition of Shaanxi Universities, exhibited",
  },
  {
    year: "2024",
    seriesId: "new-year-elevator",
    workZh: "《新年电梯》",
    workEn: "New Year Elevator",
    eventZh: "A Frame 浓缩城市计划，参展",
    eventEn: "A Frame Condensed City Project, exhibited",
    detailId: "new-year-elevator",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "第12届学院摄影奖暨第12届学院优秀摄影作品展，金奖",
    eventEn: "12th Academy Photography Award and 12th Academy Outstanding Photography Works Exhibition, Gold Award",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "第四届“未来·星丛”奖美术与书法优秀作品展，入选/参展",
    eventEn: "4th Future Star Cluster Award Art and Calligraphy Exhibition, selected and exhibited",
    detailId: "yishu-sichuan",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "第24届平遥国际摄影大展，院校优秀奖",
    eventEn: "24th Pingyao International Photography Festival, Outstanding Academy Award",
    detailId: "yishu-pingyao",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "法国阿尔勒 Fisheye “10sur10” 展览，参展",
    eventEn: "Fisheye “10sur10” Exhibition, Arles, France, exhibited",
    detailId: "yishu-arles",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "第六届1839摄影奖，入围",
    eventEn: "6th 1839 Photography Award, shortlisted",
  },
  {
    year: "2024",
    seriesId: "epitaph",
    workZh: "《疑树》",
    workEn: "Epitaph",
    eventZh: "2024届“无界西美”西安美术学院毕业季展览，一等奖",
    eventEn: "2024 Wujie Ximei Graduation Season Exhibition, Xi'an Academy of Fine Arts, First Prize",
    detailId: "yishu-xian",
  },
  {
    year: "2023",
    seriesId: "upstream-wind",
    workZh: "《上游的风》",
    workEn: "ON THE WAY",
    eventZh: "第10届学院优秀摄影作品展暨第10届学院摄影奖，优秀作品奖",
    eventEn: "10th Academy Outstanding Photography Works Exhibition and 10th Academy Photography Award, Outstanding Work Award",
  },
];
